export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const UPDATE_SKILLS = "UPDATE_SKILLS";

export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";

export const UPDATE_PROJECT = "UPDATE_PROJECT";

export const UPDATE_EDUCATION = "UPDATE_EDUCATION";

export const UPDATE_TEMPLATE = "UPDATE_TEMPLATE";

export const UPDATE_NEW_USER = "UPDATE_NEW_USER";
